# Setup
title:            Nikita Mounier
tagline:          'A programming adventure'
description:      'A programming adventure.'
url:              https://nikitamounier.github.io
baseurl:          /
paginate:         5
excerpt_separator: "<!--more-->"

# About and contact
author:
  name:           'Nikita Mounier'
  url:            https://twitter.com/nikitamounier

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
