# Setup
title:            Nikita Mounier
tagline:          'Website'
description:      'A brazen two-column <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              nikitamounier.github.io/
baseurl:          https://nikitamounier.github.io/
paginate:         5

# About and contact
author:
  name:           'Nikita Mounier'
  url:            https://twitter.com/nikitamounier

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
